export const skillsData = [
  {
    title: 'Разработка на React',
    description: 'Современная разработка на React с использованием TypeScript, Hooks и Redux',
    images: ['', ''],
    ownerId: 1,
    categoryName: 'IT и программирование',
    subcategoryName: 'Frontend',
  },
  {
    title: 'Автоматическое тестирование',
    description: 'Написание end-to-end тестов с использованием Cypress и Jest',
    images: ['', ''],
    ownerId: 2,
    categoryName: 'IT и программирование',
    subcategoryName: 'Frontend',
  },
  {
    title: 'UX/UI дизайн',
    description: 'Создание пользовательских интерфейсов и прототипов в Figma',
    images: ['', ''],
    ownerId: 1,
    categoryName: 'Дизайн и UX/UI',
    subcategoryName: 'UX/UI',
  },
  {
    title: 'Backend на Node.js',
    description: 'Разработка серверных приложений на Node.js с Express и MongoDB',
    images: ['', ''],
    ownerId: 2,
    categoryName: 'IT и программирование',
    subcategoryName: 'Backend',
  },
  {
    title: 'Графический дизайн',
    description: 'Создание логотипов, брендбуков и полиграфии в Adobe Illustrator',
    images: ['', ''],
    ownerId: 1,
    categoryName: 'Дизайн и UX/UI',
    subcategoryName: 'Графический дизайн',
  },
  {
    title: 'Мобильная разработка',
    description: 'Разработка мобильных приложений на React Native и Flutter',
    images: ['', ''],
    ownerId: 2,
    categoryName: 'IT и программирование',
    subcategoryName: 'Мобильная разработка',
  },
  {
    title: 'Игра на гитаре',
    description: 'Обучение игре на акустической и электрогитаре с нуля',
    images: ['guitar1.png', 'guitar2.png'],
    ownerId: 1,
    categoryName: 'Музыкальные инструменты',
    subcategoryName: 'Гитара',
  },
  {
    title: 'Таргетированная реклама',
    description: 'Настройка и ведение рекламных кампаний в социальных сетях',
    images: ['', ''],
    ownerId: 2,
    categoryName: 'Маркетинг и продажи',
    subcategoryName: 'Таргетинг',
  },
];